name: CI

on:
  push:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest:host
    steps:
      - name: Installer Node
        run: |
          apt-get update
          apt-get install -y nodejs npm

      - name: Installer dépendances
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format:check

      - name: Tests
        run: npm test